### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by alexgarciavila** [rtstrats/hw2-spy#2]
## Describe the bug
When you use params to show 3vs3 or 2vs2, program crash with "FileNotFoundError: [Errno 2] No such file or directory" error.

## To Reproduce
`python .\__main__.py -k myultrasecretapikey --red gerriel --yellow n0b1t --orange shadowstyle360 --tui`
**Result: Crash**

`python .\__main__.py -k myultrasecretapikey --red gerriel --yellow n0b1t --tui`
**Result: Crash**

`python .\__main__.py -k myultrasecretapikey --red gerriel --tui`
**Result: Run ok, but no games played**

`python .\__main__.py -k myultrasecretapikey --blue gerriel --cyan n0b1t --green shadowstyle360 --tui`
Result: Crash

`python .\__main__.py -k myultrasecretapikey --blue gerriel --cyan n0b1t --tui`
**Result: Crash**

`python .\__main__.py -k myultrasecretapikey --blue gerriel --tui`
**Result: Run ok, but no games played**

## Expected behavior
Run program in tui mode showing the player stats

## Priority
P2

## Screenshots/Video
![20230926-5115](https://github.com/rtstrats/hw2-spy/assets/55148944/270e8f89-d7b1-4556-827f-8e4cf4338cfe)

## Desktop
 - OS: Windows 11
 - Windows Terminal - Powershell (7.3.6)
 - Resolution 3440x1440

## Additional context
If folders "cache/matches/events" was created manually, program runs fine.
Possible issue with folder slashes

**Comment by alexgarciavila** [comment]
Found solution. Program won't check if folder "cache/matches/events" exist and raise errror.

**Comment by jmhoms** [comment]
Solved in version 1.1.2

**Comment by jmhoms** [comment]
Solved in version 1.1.2
